import { useEffect, useState } from "react";
import { Activity, RefreshCw, Power } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { runtimeBindingsApi, settingsApi, type RuntimeBinding } from "@/services/api";

export function RuntimeBindingsPage() {
  const [bindings, setBindings] = useState<RuntimeBinding[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [limits, setLimits] = useState({ global: 4, wait_seconds: 300, review_rounds: 3 });
  const [limitsSaved, setLimitsSaved] = useState(false);
  const load = async () => { try { setBindings(await runtimeBindingsApi.list()); setError(null); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } };
  useEffect(() => { void load(); void settingsApi.get("parallel_limits").then((value) => { const v = value.value as Partial<typeof limits> | undefined; if (v) setLimits((old) => ({ ...old, ...v })); }).catch(() => undefined); }, []);
  async function saveLimits() { setLimitsSaved(false); await settingsApi.update("parallel_limits", limits); setLimitsSaved(true); }
  async function update(id: string, operation: () => Promise<RuntimeBinding>) { setBusy(id); try { const next = await operation(); setBindings((all) => all.map((b) => b.id === id ? next : b)); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); } }
  return <div className="mx-auto flex w-full max-w-4xl flex-col gap-5">
    <div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Central de RuntimeBindings</h2><p className="text-xs text-muted-foreground">Capacidade, saúde e fila por instalação autenticada.</p></div><Button size="sm" variant="outline" onClick={() => void load()}><RefreshCw className="size-4" /> Recarregar</Button></div>
    {error && <p role="alert" className="rounded border border-destructive/40 p-2 text-xs text-destructive">{error}</p>}
    <section className="rounded-lg border border-border p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-medium">Limites de execução</h3><p className="text-xs text-muted-foreground">Novas sessões aguardam na fila; sessões em andamento não são interrompidas.</p></div><Button size="sm" onClick={() => void saveLimits()}><SaveIcon /> Salvar</Button></div><div className="mt-3 grid grid-cols-3 gap-3 text-xs"><label>Global<input className="mt-1 h-8 w-full rounded border bg-transparent px-2" type="number" min={1} max={64} value={limits.global} onChange={(e) => setLimits({ ...limits, global: Math.max(1, Number(e.target.value) || 1) })} /></label><label>Espera (s)<input className="mt-1 h-8 w-full rounded border bg-transparent px-2" type="number" min={1} max={7200} value={limits.wait_seconds} onChange={(e) => setLimits({ ...limits, wait_seconds: Math.max(1, Number(e.target.value) || 1) })} /></label><label>Ciclos de review<input className="mt-1 h-8 w-full rounded border bg-transparent px-2" type="number" min={1} max={8} value={limits.review_rounds} onChange={(e) => setLimits({ ...limits, review_rounds: Math.max(1, Number(e.target.value) || 1) })} /></label></div>{limitsSaved && <p className="mt-2 text-xs text-emerald-600">Limites persistidos.</p>}</section>
    {bindings.length === 0 ? <p className="rounded border border-dashed p-5 text-sm text-muted-foreground">Nenhum runtime detectado. Configure o CLI fora do AgentMash e recarregue.</p> : <div className="grid gap-3 md:grid-cols-2">{bindings.map((b) => { const available = Math.max(0, Math.min(b.observed_capacity, b.configured_capacity) - b.reserved_slots); return <section key={b.id} className="rounded-lg border border-border p-4" data-testid="runtime-binding-card"><div className="flex items-start justify-between gap-2"><div><h3 className="font-medium">{b.label}</h3><p className="text-xs text-muted-foreground">{b.provider_id} · {b.id}</p></div><Badge variant={b.enabled ? "secondary" : "outline"}>{b.enabled ? b.health : "desativado"}</Badge></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div><strong className="block text-base">{b.configured_capacity}</strong>configurados</div><div><strong className="block text-base">{b.reserved_slots}</strong>ocupados</div><div><strong className="block text-base">{available}</strong>disponíveis</div></div><div className="mt-3 flex items-center gap-2"><label className="flex flex-1 items-center gap-2 text-xs">Limite <input aria-label={`Limite ${b.label}`} className="h-8 w-16 rounded border bg-transparent px-2" type="number" min={1} max={32} defaultValue={b.configured_capacity} onBlur={(e) => { const value = Number(e.target.value); if (value >= 1 && value <= 32 && value !== b.configured_capacity) void update(b.id, () => runtimeBindingsApi.setCapacity(b.id, value)); }} /></label><Button title="Reconciliar slots" size="icon" variant="outline" disabled={busy === b.id} onClick={() => void update(b.id, () => runtimeBindingsApi.reconcile(b.id))}><Activity className="size-4" /></Button><Button title={b.enabled ? "Desativar" : "Ativar"} size="icon" variant="outline" disabled={busy === b.id} onClick={() => void update(b.id, () => runtimeBindingsApi.setEnabled(b.id, !b.enabled))}><Power className="size-4" /></Button></div>{b.last_diagnostic && <p className="mt-2 text-xs text-muted-foreground">Diagnóstico: {b.last_diagnostic}</p>}</section>})}</div>}
  </div>;
}

function SaveIcon() { return <span aria-hidden="true">✓</span>; }
