import type { ReactNode } from 'react';
import type { DeploymentEnvironmentSummary, DeploymentIncidentDTO, DeploymentLogDTO, DeploymentPhaseTelemetryDTO, DeploymentRunDetail, ReleaseCandidateDetail } from '@/types/deployment';

export function DeploymentPanel({ title, children }: { title: string; children: ReactNode }) { return <section className="deployment-panel" aria-label={title}><h2>{title}</h2>{children}</section>; }
export function Pipeline({ environments, detail }: { environments: DeploymentEnvironmentSummary[]; detail: ReleaseCandidateDetail | null }) {
  const names = ['development', 'staging', 'production'] as const;
  return <ol className="deployment-pipeline" aria-label="Pipeline de ambientes">{names.map(name => { const env = environments.find(item => item.name === name); const state = detail?.environments_status[name]; return <li key={name} className={state?.is_current ? 'current' : ''}><strong>{env?.display_name ?? name}</strong><span>{state?.status ?? env?.observed_state ?? 'não configurado'}</span>{env?.current_release_sha && <code title={env.current_release_sha}>{env.current_release_sha.slice(0, 8)}</code>}</li>; })}</ol>;
}
export function RunEvidence({ run }: { run: DeploymentRunDetail | null }) { if (!run) return <p>Nenhuma execução selecionada.</p>; return <div className="deployment-grid"><dl><dt>Estado</dt><dd>{run.run.status}</dd><dt>SHA</dt><dd><code>{run.run.target_sha}</code></dd><dt>Tentativa</dt><dd>{run.run.current_attempt_number}</dd><dt>Iniciado por</dt><dd>{run.run.initiated_by}</dd></dl><div><h3>Jobs e operações</h3><ul>{run.attempts.map(attempt => <li key={attempt.id}>{attempt.attempt_number}: {attempt.status} {attempt.provider_run_url && <a href={attempt.provider_run_url} target="_blank" rel="noreferrer">workflow</a>}</li>)}</ul></div></div>; }
export function Logs({ logs }: { logs: DeploymentLogDTO[] }) { return <div className="deployment-log" aria-label="Logs sanitizados">{logs.length ? logs.map(log => <p key={log.id}><time>{log.timestamp}</time> <strong>{log.log_level}</strong> {log.message_sanitized}</p>) : <p>Nenhum log sanitizado disponível.</p>}</div>; }
export function Telemetry({ telemetry }: { telemetry: DeploymentPhaseTelemetryDTO[] }) { return <ul className="deployment-telemetry">{telemetry.length ? telemetry.map(item => <li key={item.id}><strong>{item.phase_name}</strong><span>{item.status}</span><span>{item.duration_ms === null ? 'não medido' : `${item.duration_ms} ms`}</span></li>) : <li>Nenhuma telemetria disponível.</li>}</ul>; }
export function Incidents({ incidents }: { incidents: DeploymentIncidentDTO[] }) { return <ul>{incidents.length ? incidents.map(incident => <li key={incident.id}><strong>{incident.severity}: {incident.title}</strong><p>{incident.description}</p><p>Ação sugerida: {incident.suggested_action}</p></li>) : <li>Nenhum incidente registrado.</li>}</ul>; }
