/** Wire DTOs for Milestone 5. Datetimes are UTC ISO-8601 strings. */
export type DeploymentEnvironmentName = 'development' | 'staging' | 'production';
export type DeploymentProvider = 'github_actions';
export type ReleaseStatus = 'draft' | 'ready_for_predeploy' | 'predeploy_running' | 'predeploy_failed' | 'awaiting_development_approval' | 'deploying_development' | 'development_verification' | 'development_failed' | 'development_ready' | 'awaiting_staging_approval' | 'deploying_staging' | 'staging_verification' | 'staging_failed' | 'staging_ready' | 'awaiting_production_approval' | 'deploying_production' | 'production_verification' | 'production_failed' | 'production_healthy' | 'rollback_proposed' | 'awaiting_rollback_approval' | 'rolling_back' | 'rollback_verification' | 'rolled_back' | 'rollback_failed' | 'blocked' | 'cancelled';
export type DeploymentRunStatus = 'pending' | 'leased' | 'in_flight' | 'verifying' | 'succeeded' | 'failed' | 'cancelled' | 'blocked';
export type ApprovalAction = 'deploy_development' | 'deploy_staging' | 'deploy_production' | 'rollback_production' | 'promote';

export interface ApprovalPolicyDTO { required_roles: string[]; min_approvals: number; allow_same_author: boolean; reinforced_production: boolean; }
export interface DeploymentEnvironmentSummary { id: string; project_id: string; name: DeploymentEnvironmentName; display_name: string; provider: DeploymentProvider; remote_identifier: string; observed_state: 'idle' | 'deploying' | 'verifying' | 'healthy' | 'unhealthy' | 'blocked'; current_release_id: string | null; current_release_sha: string | null; last_healthy_release_id: string | null; last_healthy_release_sha: string | null; active_lease_holder: string | null; created_at: string; updated_at: string; }
export interface DeploymentBindingInput { project_id: string; environment_id: string; provider: DeploymentProvider; remote_url: string; repo_name: string; target_branch: string; workflow_file: string; environment_name: string; }
export interface DeploymentBindingDTO extends DeploymentBindingInput { id: string; is_active: boolean; created_at: string; updated_at: string; }
export interface HealthCheckProfileDTO { id: string; project_id: string; environment_id: string; name: string; check_type: 'http_get' | 'local_command'; target: string; expected_status: number | null; expected_body_substring: string | null; timeout_seconds: number; max_retries: number; retry_interval_seconds: number; observation_period_seconds: number; headers_secret_ref: string | null; is_active: boolean; created_at: string; updated_at: string; }
export interface DeploymentRunSummaryDTO { id: string; project_id: string; release_candidate_id: string; environment_id: string; environment_name: DeploymentEnvironmentName; target_sha: string; status: DeploymentRunStatus; idempotency_key: string; current_attempt_number: number; initiated_by: string; error_message: string | null; started_at: string | null; completed_at: string | null; created_at: string; updated_at: string; }
export interface DeploymentEnvironmentDetail { environment: DeploymentEnvironmentSummary; binding: DeploymentBindingDTO | null; health_profile: HealthCheckProfileDTO | null; approval_policy: ApprovalPolicyDTO; active_run: DeploymentRunSummaryDTO | null; recent_runs: DeploymentRunSummaryDTO[]; }
export interface ReleaseCandidateSummary { id: string; project_id: string; delivery_candidate_id: string; version: number; target_sha: string; source_branch: string; status: ReleaseStatus; risk_level: 'low' | 'medium' | 'high' | 'critical'; current_environment: string | null; has_pending_approvals: boolean; created_by: string; created_at: string; updated_at: string; }
export interface ReleaseSnapshotDTO { id: string; release_candidate_id: string; version: number; target_sha: string; artifacts_hash: string; manifest: Record<string, unknown>; evidence_summary: Record<string, unknown>; created_at: string; }
export interface DeploymentApprovalDTO { id: string; project_id: string; release_candidate_id: string; deployment_run_id: string | null; environment_id: string; action: ApprovalAction; status: 'pending' | 'approved' | 'rejected'; actor_id: string; actor_role: string; comment: string | null; approved_at: string | null; metadata: Record<string, unknown>; created_at?: string; }
export interface PromotionRequestDTO { id: string; project_id: string; release_candidate_id: string; from_environment_id: string; to_environment_id: string; status: 'pending' | 'approved' | 'rejected' | 'in_progress' | 'completed' | 'cancelled'; requested_by: string; target_sha: string; created_at: string; updated_at: string; }
export interface DeploymentAttemptDTO { id: string; deployment_run_id: string; attempt_number: number; status: 'running' | 'succeeded' | 'failed' | 'cancelled'; provider_run_id: string | null; provider_run_url: string | null; failure_reason: string | null; started_at: string; completed_at: string | null; }
export interface DeploymentOperationDTO { id: string; deployment_run_id: string; idempotency_key: string; operation_type: 'dispatch_workflow' | 'cancel_workflow' | 'poll_workflow' | 'execute_rollback'; provider: string; remote_id: string | null; status: 'pending' | 'in_flight' | 'succeeded' | 'failed'; request_payload_sanitized: Record<string, unknown>; response_payload_sanitized: Record<string, unknown>; created_at: string; updated_at: string; }
export interface DeploymentLogDTO { id: string; deployment_run_id: string; attempt_number: number; log_level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'; message_sanitized: string; source: string; timestamp: string; }
export interface HealthCheckResultDTO { id: string; deployment_run_id: string; profile_id: string; status: 'passed' | 'failed' | 'timed_out'; status_code: number | null; response_time_ms: number | null; details_sanitized: Record<string, unknown>; error_message: string | null; checked_at: string; }
export interface DeploymentIncidentDTO { id: string; deployment_run_id: string; environment_id: string; severity: 'P0' | 'P1' | 'P2' | 'P3'; title: string; description: string; root_cause: string | null; suggested_action: string; is_resolved: boolean; resolved_at: string | null; created_at: string; }
export interface DeploymentRollbackPlanDTO { id: string; project_id: string; deployment_run_id: string; environment_id: string; current_release_id: string; target_release_id: string; target_sha: string; rollback_strategy: 'previous_healthy' | 'specific_release'; impact_summary: string; risk_assessment: string; status: 'proposed' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed'; created_at: string; }
export interface DeploymentRollbackExecutionDTO { id: string; rollback_plan_id: string; status: 'running' | 'succeeded' | 'failed'; initiated_by: string; provider_run_id: string | null; provider_run_url: string | null; post_verification_status: 'pending' | 'passed' | 'failed'; error_message: string | null; executed_at: string; completed_at: string | null; }
export interface DeploymentPhaseTelemetryDTO { id: string; deployment_run_id: string; phase_name: string; duration_ms: number | null; queue_wait_ms: number | null; human_wait_ms: number | null; started_at: string; ended_at: string | null; status: string; }
export interface DeploymentInternalStepDTO { id: string; deployment_run_id: string; step_name: string; status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped'; started_at: string; completed_at: string | null; metadata: Record<string, unknown>; }
export interface DeploymentRecoveryStateDTO { is_blocked: boolean; recovery_reason: string | null; suggested_action: string | null; active_leases: Array<{ environment_id: string; held_by_run_id: string; expires_at: string }>; reconciled_runs_count: number; }
/** The contract names this response but intentionally does not freeze its shape. */
export type PredeployReportDTO = Record<string, unknown>;
export interface DeploymentRunDetail { run: DeploymentRunSummaryDTO; attempts: DeploymentAttemptDTO[]; operations: DeploymentOperationDTO[]; logs: DeploymentLogDTO[]; health_results: HealthCheckResultDTO[]; incidents: DeploymentIncidentDTO[]; telemetry: DeploymentPhaseTelemetryDTO[]; internal_steps: DeploymentInternalStepDTO[]; }
export interface ReleaseCandidateDetail { release_candidate: ReleaseCandidateSummary; snapshot: ReleaseSnapshotDTO; delivery_candidate_summary: { id: string; version: number; base_sha: string; integration_sha: string; merged_at: string; }; environments_status: Record<string, { status: string; deployed_at: string | null; is_current: boolean; is_healthy: boolean }>; approvals: DeploymentApprovalDTO[]; promotions: PromotionRequestDTO[]; current_runs: DeploymentRunSummaryDTO[]; rollback_plan: DeploymentRollbackPlanDTO | null; recovery: DeploymentRecoveryStateDTO | null; telemetry: DeploymentPhaseTelemetryDTO[]; internal_steps: DeploymentInternalStepDTO[]; }
