import { beforeEach, describe, expect, it, vi } from 'vitest';
import { deploymentApi } from '@/services/deploymentApi';
import { onBridgeEvent } from '@/services/bridge';
import { useDeploymentStore } from '@/stores/deploymentStore';
vi.mock('@/services/bridge', () => ({ onBridgeEvent: vi.fn() }));
vi.mock('@/services/deploymentApi', () => ({ deploymentApi: { listEnvironments: vi.fn(), listReleases: vi.fn(), getRelease: vi.fn() } }));
const summary = { id: 'r', project_id: 'p', delivery_candidate_id: 'd', version: 1, target_sha: 'a'.repeat(40), source_branch: 'main', status: 'production_healthy', risk_level: 'low', current_environment: 'production', has_pending_approvals: false, created_by: 'creator', created_at: 'now', updated_at: 'now' } as const;
const detail = { release_candidate: summary, snapshot: { id: 's', release_candidate_id: 'r', version: 1, target_sha: summary.target_sha, artifacts_hash: 'b'.repeat(64), manifest: {}, evidence_summary: {}, created_at: 'now' }, delivery_candidate_summary: { id: 'd', version: 1, base_sha: 'a', integration_sha: 'b', merged_at: 'now' }, environments_status: {}, approvals: [], promotions: [], current_runs: [], rollback_plan: null, recovery: null, telemetry: [], internal_steps: [] };
beforeEach(() => { vi.clearAllMocks(); useDeploymentStore.setState({ projectId: null, environments: [], releases: [], selectedReleaseId: null, detail: null, runDetail: null, recovery: null, loading: false, busy: false, error: null, liveEvent: null }); vi.mocked(deploymentApi.listEnvironments).mockResolvedValue([]); vi.mocked(deploymentApi.listReleases).mockResolvedValue([summary]); vi.mocked(deploymentApi.getRelease).mockResolvedValue(detail); });
describe('deploymentStore', () => {
  it('loads persisted release detail and does not invent success state', async () => { await useDeploymentStore.getState().load('p'); expect(useDeploymentStore.getState().detail).toEqual(detail); expect(useDeploymentStore.getState().error).toBeNull(); });
  it('refreshes once after a burst of deployment events', async () => { let listener!: (event: { event: string; payload: Record<string, unknown> }) => void; const stop = vi.fn(); vi.mocked(onBridgeEvent).mockImplementation(async callback => { listener = callback; return stop; }); useDeploymentStore.setState({ projectId: 'p', selectedReleaseId: 'r' }); const dispose = useDeploymentStore.getState().subscribe(); await Promise.resolve(); listener({ event: 'deployment:run_updated', payload: { project_id: 'p', release_candidate_id: 'r' } }); listener({ event: 'deployment:health_check_completed', payload: { project_id: 'p', release_candidate_id: 'r' } }); await new Promise(resolve => setTimeout(resolve, 240)); expect(deploymentApi.listReleases).toHaveBeenCalled(); dispose(); expect(stop).toHaveBeenCalledOnce(); });
  it('ignores unrelated events', async () => { let listener!: (event: { event: string; payload: Record<string, unknown> }) => void; vi.mocked(onBridgeEvent).mockImplementation(async callback => { listener = callback; return () => undefined; }); useDeploymentStore.setState({ projectId: 'p', selectedReleaseId: 'r' }); const dispose = useDeploymentStore.getState().subscribe(); await Promise.resolve(); listener({ event: 'deployment:run_updated', payload: { project_id: 'other' } }); await new Promise(resolve => setTimeout(resolve, 240)); expect(deploymentApi.listReleases).not.toHaveBeenCalled(); dispose(); });
});
