import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { DeploymentCenterPage } from '@/pages/DeploymentCenterPage';
import { useDeploymentStore } from '@/stores/deploymentStore';
vi.mock('@/services/bridge', () => ({ onBridgeEvent: vi.fn().mockResolvedValue(() => undefined) }));
beforeEach(() => { useDeploymentStore.setState({ projectId: null, environments: [], releases: [], selectedReleaseId: null, detail: null, runDetail: null, recovery: null, loading: false, busy: false, error: null, liveEvent: null }); });
afterEach(cleanup);
describe('DeploymentCenterPage', () => {
  it('renders an accessible empty state without optimistic success', () => { render(<DeploymentCenterPage />); expect(screen.getByRole('heading', { name: 'Deployment Center' })).toBeInTheDocument(); expect(screen.getByLabelText('Project ID')).toBeInTheDocument(); });
  it('renders blocked and approval UI from persisted state', () => { useDeploymentStore.setState({ projectId: 'p', releases: [{ id: 'r', project_id: 'p', delivery_candidate_id: 'd', version: 1, target_sha: 'a'.repeat(40), source_branch: 'main', status: 'blocked', risk_level: 'high', current_environment: null, has_pending_approvals: true, created_by: 'creator', created_at: 'now', updated_at: 'now' }], selectedReleaseId: 'r', detail: { release_candidate: { id: 'r', project_id: 'p', delivery_candidate_id: 'd', version: 1, target_sha: 'a'.repeat(40), source_branch: 'main', status: 'blocked', risk_level: 'high', current_environment: null, has_pending_approvals: true, created_by: 'creator', created_at: 'now', updated_at: 'now' }, snapshot: { id: 's', release_candidate_id: 'r', version: 1, target_sha: 'a'.repeat(40), artifacts_hash: 'b'.repeat(64), manifest: {}, evidence_summary: {}, created_at: 'now' }, delivery_candidate_summary: { id: 'd', version: 1, base_sha: 'a', integration_sha: 'b', merged_at: 'now' }, environments_status: {}, approvals: [], promotions: [], current_runs: [], rollback_plan: null, recovery: { is_blocked: true, recovery_reason: 'lease_expired', suggested_action: 'reconcile', active_leases: [], reconciled_runs_count: 0 }, telemetry: [], internal_steps: [] } }); render(<DeploymentCenterPage />); expect(screen.getByRole('alert')).toHaveTextContent('lease_expired'); expect(screen.getByRole('button', { name: 'Aprovar' })).toBeDisabled(); });
});
