import raw from "@/game/maps/agentmashHq.json";
import type { RoomId } from "@/game/maps/roomTypes";

/**
 * Pure, Phaser-free reader for the real Tiled JSON map
 * (`agentmashHq.json`, generated by `scripts/generate_office_map.py`).
 * Every grid fact used anywhere in the app -- collision, room bounds,
 * named destinations -- is derived here from that one file, not
 * hardcoded in TypeScript, so this module and the Phaser scene that
 * renders the same file can never drift apart.
 */

interface TiledTileLayer {
  type: "tilelayer";
  name: string;
  data: number[];
}

interface TiledObject {
  id: number;
  name: string;
  type: string;
  x: number;
  y: number;
  width: number;
  height: number;
  point?: boolean;
  properties?: { name: string; value: string }[];
}

interface TiledObjectLayer {
  type: "objectgroup";
  name: string;
  objects: TiledObject[];
}

type TiledLayer = TiledTileLayer | TiledObjectLayer;

interface TiledMap {
  width: number;
  height: number;
  tilewidth: number;
  tileheight: number;
  layers: TiledLayer[];
}

const map = raw as unknown as TiledMap;

export const TILE_SIZE = map.tilewidth;
export const MAP_COLS = map.width;
export const MAP_ROWS = map.height;

/** The raw Tiled JSON, for `BootScene` to hand directly to Phaser's
 * tilemap cache (`this.cache.tilemap.add`) -- avoids needing the file
 * served at a fetchable URL, since Vite already bundled it here. */
export const RAW_TILED_MAP = raw;

function tileLayer(name: string): TiledTileLayer {
  const found = map.layers.find((l): l is TiledTileLayer => l.type === "tilelayer" && l.name === name);
  if (!found) throw new Error(`agentmashHq.json: missing tile layer "${name}"`);
  return found;
}

function objectLayer(name: string): TiledObjectLayer {
  const found = map.layers.find((l): l is TiledObjectLayer => l.type === "objectgroup" && l.name === name);
  if (!found) throw new Error(`agentmashHq.json: missing object layer "${name}"`);
  return found;
}

const collisionData = tileLayer("Collision").data;

/** The single source of truth for walkability -- read directly from the
 * map's dedicated Collision layer (drawn in Tiled/generated alongside
 * the walls and furniture that produced it), never re-derived from room
 * rectangle math in application code. */
export function isWalkable(x: number, y: number): boolean {
  if (x < 0 || y < 0 || x >= MAP_COLS || y >= MAP_ROWS) return false;
  return collisionData[y * MAP_COLS + x] === 0;
}

export interface RoomDefinition {
  id: RoomId;
  label: string;
  /** Inclusive tile rectangle. */
  rect: [number, number, number, number];
}

const ROOM_LABELS: Record<RoomId, string> = {
  ceo_office: "CEO Office",
  meeting_room: "Meeting Room",
  frontend_desk: "Frontend Room",
  backend_desk: "Backend Room",
  design_desk: "Design Room",
  testing_lab: "Testing Lab",
  lounge: "Lounge",
  recovery_room: "Recovery Room",
};

function propertyValue(obj: TiledObject, key: string): string | undefined {
  return obj.properties?.find((p) => p.name === key)?.value;
}

export const ROOMS: RoomDefinition[] = objectLayer("Zones").objects.map((obj) => {
  const roomId = (propertyValue(obj, "room") ?? obj.name) as RoomId;
  const x1 = Math.round(obj.x / TILE_SIZE);
  const y1 = Math.round(obj.y / TILE_SIZE);
  const x2 = Math.round((obj.x + obj.width) / TILE_SIZE) - 1;
  const y2 = Math.round((obj.y + obj.height) / TILE_SIZE) - 1;
  return { id: roomId, label: ROOM_LABELS[roomId] ?? roomId, rect: [x1, y1, x2, y2] };
});

const ROOM_BY_ID = new Map(ROOMS.map((r) => [r.id, r]));

export function roomLabel(room: RoomId): string {
  return ROOM_BY_ID.get(room)?.label ?? room;
}

/** Which room (if any) contains a given tile -- used both by the debug
 * "Current Room" HUD and by anything that needs to know where an agent
 * physically is. */
export function roomAt(x: number, y: number): RoomId | null {
  for (const room of ROOMS) {
    const [x1, y1, x2, y2] = room.rect;
    if (x >= x1 && x <= x2 && y >= y1 && y <= y2) return room.id;
  }
  return null;
}

const spawnObjects = objectLayer("SpawnPoints").objects;

function pointTile(obj: TiledObject): [number, number] {
  return [Math.floor(obj.x / TILE_SIZE), Math.floor(obj.y / TILE_SIZE)];
}

const SPAWN_BY_NAME = new Map(spawnObjects.map((o) => [o.name, pointTile(o)]));

/** Where every autonomous agent enters the building before the state
 * machine sends it to its actual desk -- there is no user-controlled
 * character to spawn here anymore (Stage 2 removed the Owner). */
export const AGENTS_ENTRY: [number, number] = SPAWN_BY_NAME.get("agents_entry") ?? [1, 1];

export function destinationPoint(destination: string): [number, number] {
  const point = SPAWN_BY_NAME.get(destination);
  if (!point) throw new Error(`agentmashHq.json: unknown destination "${destination}"`);
  return point;
}

export interface InteractiveObjectDefinition {
  id: string;
  type: string;
  tile: [number, number];
  room: RoomId | null;
}

export const INTERACTIVE_OBJECTS: InteractiveObjectDefinition[] = objectLayer("Objects").objects.map((obj) => ({
  id: obj.name,
  type: obj.type,
  tile: pointTile(obj),
  room: (propertyValue(obj, "room") as RoomId | undefined) ?? null,
}));
